services:
  micro_annonces:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6061:6061
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"