package com.crm.crmms.entities;

public enum EPartnershipType {
    FUSION,
    ACQUISITION,
    STRATEGIC_PARTNERSHIP,
    JOINT_VENTURE,
    BUSINESS_ALLIANCE,
    DISTRIBUTION_AGREEMENT,
    LICENSING_AGREEMENT,
    CO_DEVELOPMENT_AGREEMENT,
    TECHNOLOGY_PARTNERSHIP,
    JOINT_PRODUCT_DEVELOPMENT
}
